name: Trigger auto deployment for container-app-4rmtb5qcsavjy

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-4rmtb5qcsavjy-AutoDeployTrigger-d791cea4-c311-43be-9ce0-fd393fa3bb63.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP4RMTB5QCSAVJY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP4RMTB5QCSAVJY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP4RMTB5QCSAVJY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry4rmtb5qcsavjy.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP4RMTB5QCSAVJY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP4RMTB5QCSAVJY_REGISTRY_PASSWORD }}
          containerAppName: container-app-4rmtb5qcsavjy
          resourceGroup: todonodejsmongo87638593
          imageToBuild: containerregistry4rmtb5qcsavjy.azurecr.io/container-app-4rmtb5qcsavjy:${{ github.sha }}
          


